version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tihomir!Strong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./src/main/resources/init.sql:/init.sql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Tihomir!Strong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  db-init:
    image: mcr.microsoft.com/mssql-tools
    volumes:
      - ./src/main/resources/init.sql:/init.sql
    restart: on-failure
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'Tihomir!Strong@Passw0rd' -d master -i /init.sql